alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
databases:
- engine: PG
  name: db
  num_nodes: 1
  size: db-s-dev-database
  version: "12"
name: holiday-api
region: fra
services:
- build_command: yarn build
  environment_slug: node-js
  envs:
  - key: DATABASE_URL
    scope: RUN_TIME
    value: ${db.DATABASE_URL}
  github:
    branch: master
    deploy_on_push: true
    repo: cedricwider/holiday-api
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  name: holiday-api
  routes:
  - path: /
  run_command: yarn start
  source_dir: /
